### ISSUE TITLE
bad_request_400.BotMethodInvalid

### ISSUE THREAD

**Issue by Gingerchairrr** [Dineshkarthik/telegram_media_downloader#105]
**Describe the bug**
I installed the python and this program, run the python script at windows power shell, and it said "pyrogram.errors.exceptions.bad_request_400.BotMethodInvalid: [400 BOT_METHOD_INVALID]: The method can't be used by bots (caused by "messages.GetHistory")"
**To Reproduce**
Share the config: `Please don't share your api_hash & api_id`
```yaml
chat_id: 694522718
last_read_message_id: 3


media_types:
- audio
- photo
- video
- document
- voice
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
```

**Python Version**
Python: [3.9.6]

**OS:**
The OS and its version: [Windows 10 2004]

**Logs**
PS C:\Users\hello> cd Z:\TelegramMedia\telegram_media_downloader
PS Z:\TelegramMedia\telegram_media_downloader> py media_downloader.py
Telegram Media Downloader v1.0.0, Copyright (C) 2019 Dineshkarthik <https://github.com/Dineshkarthik>
Licensed under the terms of the MIT License

INFO:media_downloader:Device: CPython 3.9.6 - Telegram Media Downloader 1.0.0
INFO:media_downloader:System: Windows 10 (EN)
INFO:pyrogram.connection.transport.tcp.tcp:Using proxy 127.0.0.1:7890
INFO:pyrogram.connection.connection:Connecting...
INFO:pyrogram.connection.connection:Connected! Production DC5 - IPv4 - TCPAbridgedO
INFO:pyrogram.session.session:NetworkTask started
INFO:pyrogram.session.internals.msg_id:Time synced: 2021-08-03 14:58:53.115061 UTC
INFO:pyrogram.session.session:NextSaltTask started
INFO:pyrogram.session.session:Next salt in 27m 57s (at 2021-08-03 23:26:51)
INFO:pyrogram.session.session:Session initialized: Layer 126
INFO:pyrogram.session.session:Device: CPython 3.9.6 - Pyrogram 1.2.6
INFO:pyrogram.session.session:System: Windows 10 (EN)
INFO:pyrogram.session.session:Session started
INFO:pyrogram.session.session:PingTask started
INFO:pyrogram.dispatcher:Started 20 HandlerTasks
INFO:pyrogram.syncer:Synced "media_downloader" in 27.0333 ms
Traceback (most recent call last):
  File "Z:\TelegramMedia\telegram_media_downloader\media_downloader.py", line 358, in <module>
    main()
  File "Z:\TelegramMedia\telegram_media_downloader\media_downloader.py", line 342, in main
    updated_config = asyncio.get_event_loop().run_until_complete(
  File "C:\Users\hello\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "Z:\TelegramMedia\telegram_media_downloader\media_downloader.py", line 308, in begin_import
    async for message in messages_iter:
  File "C:\Users\hello\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\methods\messages\iter_history.py", line 79, in iter_history
    messages = await self.get_history(
  File "C:\Users\hello\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\methods\messages\get_history.py", line 88, in get_history
    await self.send(
  File "C:\Users\hello\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\methods\advanced\send.py", line 77, in send
    r = await self.session.send(
  File "C:\Users\hello\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\session\session.py", line 425, in send
    return await self._send(data, timeout=timeout)
  File "C:\Users\hello\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\session\session.py", line 395, in _send
    RPCError.raise_it(result, type(data))
  File "C:\Users\hello\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\errors\rpc_error.py", line 78, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.BotMethodInvalid: [400 BOT_METHOD_INVALID]: The method can't be used by bots (caused by "messages.GetHistory")
PS Z:\TelegramMedia\telegram_media_downloader>

**Additional context**
![1](https://user-images.githubusercontent.com/88391734/128043140-9be0508f-9eec-4a9e-9d9b-7d04947e87c1.png)

**Comment by Dineshkarthik** [comment]
@Gingerchairrr how did you create the api_id and api_hash? using this - https://my.telegram.org/apps or using `BotFather`

**Comment by Gingerchairrr** [comment]
> @Gingerchairrr how did you create the api_id and api_hash? using this - https://my.telegram.org/apps or using `BotFather`
 Yes I filled the form on  https://my.telegram.org/apps to get api_id and api_hash, and BotFather get bot API token.

**Comment by swiftan** [comment]
Hey I have the same problem. Have you sovled that?

**Comment by PeiweiHu** [comment]
Two ways for authentication: (1) your phone number and verification code, and (2) your bot token. You may use the first way to avoid this: `BotMethodInvalid: [400 BOT_METHOD_INVALID]: The method can't be used by bots (caused by "messages.GetHistory")`.
