### ISSUE TITLE
bad_request_400.ChannelInvalid: [400 CHANNEL_INVALID]: The channel parameter is invalid (caused by "channels.GetChannels")

### ISSUE THREAD

**Issue by zhuoruofuqu** [Dineshkarthik/telegram_media_downloader#112]
C:\Users\ASUS\PycharmProjects\telegram—spider\venv\Scripts\python.exe C:/Users/ASUS/PycharmProjects/telegram—spider/telegram_media_downloader-master/telegram_media_downloader-master/media_downloader.py
Telegram Media Downloader v1.0.0, Copyright (C) 2019 Dineshkarthik <https://github.com/Dineshkarthik>
Licensed under the terms of the MIT License

INFO:media_downloader:Device: CPython 3.8.8 - Telegram Media Downloader 1.0.0
INFO:media_downloader:System: Windows 10 (EN)
INFO:pyrogram.connection.transport.tcp.tcp:Using proxy 127.0.0.1:7890
INFO:pyrogram.connection.connection:Connecting...
INFO:pyrogram.connection.connection:Connected! Production DC5 - IPv4 - TCPAbridgedO
INFO:pyrogram.session.session:NetworkTask started
INFO:pyrogram.session.internals.msg_id:Time synced: 2021-09-14 18:05:42.790286 UTC
INFO:pyrogram.session.session:NextSaltTask started
INFO:pyrogram.session.session:Next salt in 32m 58s (at 2021-09-15 02:38:42)
INFO:pyrogram.session.session:Session initialized: Layer 126
INFO:pyrogram.session.session:Device: CPython 3.8.8 - Pyrogram 1.2.9
INFO:pyrogram.session.session:System: Windows 10 (EN)
INFO:pyrogram.session.session:Session started
INFO:pyrogram.session.session:PingTask started
INFO:pyrogram.dispatcher:Started 20 HandlerTasks
Traceback (most recent call last):
  File "C:\Users\ASUS\PycharmProjects\telegram—spider\venv\lib\site-packages\pyrogram\methods\advanced\resolve_peer.py", line 60, in resolve_peer
    return await self.storage.get_peer_by_id(peer_id)
  File "C:\Users\ASUS\PycharmProjects\telegram—spider\venv\lib\site-packages\pyrogram\storage\sqlite_storage.py", line 147, in get_peer_by_id
    raise KeyError(f"ID not found: {peer_id}")
KeyError: 'ID not found: -1001469109660'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/ASUS/PycharmProjects/telegram—spider/telegram_media_downloader-master/telegram_media_downloader-master/media_downloader.py", line 358, in <module>
    main()
  File "C:/Users/ASUS/PycharmProjects/telegram—spider/telegram_media_downloader-master/telegram_media_downloader-master/media_downloader.py", line 342, in main
    updated_config = asyncio.get_event_loop().run_until_complete(
  File "D:\Anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:/Users/ASUS/PycharmProjects/telegram—spider/telegram_media_downloader-master/telegram_media_downloader-master/media_downloader.py", line 308, in begin_import
    async for message in messages_iter:
  File "C:\Users\ASUS\PycharmProjects\telegram—spider\venv\lib\site-packages\pyrogram\methods\messages\iter_history.py", line 79, in iter_history
    messages = await self.get_history(
  File "C:\Users\ASUS\PycharmProjects\telegram—spider\venv\lib\site-packages\pyrogram\methods\messages\get_history.py", line 90, in get_history
    peer=await self.resolve_peer(chat_id),
  File "C:\Users\ASUS\PycharmProjects\telegram—spider\venv\lib\site-packages\pyrogram\methods\advanced\resolve_peer.py", line 109, in resolve_peer
    await self.send(
  File "C:\Users\ASUS\PycharmProjects\telegram—spider\venv\lib\site-packages\pyrogram\methods\advanced\send.py", line 77, in send
    r = await self.session.send(
  File "C:\Users\ASUS\PycharmProjects\telegram—spider\venv\lib\site-packages\pyrogram\session\session.py", line 425, in send
    return await self._send(data, timeout=timeout)
  File "C:\Users\ASUS\PycharmProjects\telegram—spider\venv\lib\site-packages\pyrogram\session\session.py", line 395, in _send
    RPCError.raise_it(result, type(data))
  File "C:\Users\ASUS\PycharmProjects\telegram—spider\venv\lib\site-packages\pyrogram\errors\rpc_error.py", line 78, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ChannelInvalid: [400 CHANNEL_INVALID]: The channel parameter is invalid (caused by "channels.GetChannels")

**Comment by zhuoruofuqu** [comment]
i don't know why?please help me.thanks

**Comment by Dineshkarthik** [comment]
@zhuoruofuqu can you use the Issue template and your config without secrets like #105 ?

**Comment by zhuoruofuqu** [comment]
> @zhuoruofuqu你可以使用 Issue 模板和你的配置而没有像#105这样的秘密吗？

yes

**Comment by anonymous-Developer-i** [comment]
I'm also facing this issue ! Please someone help me

**Comment by Dineshkarthik** [comment]
> I'm also facing this issue ! Please someone help me

Please check if you have access to that channel and the channel is is correct if you already know the channel @channelName us the _channelName_ instead of the id
