### ISSUE TITLE
Not able to login via app [406 UPDATE_APP_TO_LOGIN]

### ISSUE THREAD

**Issue by Wurzelmann** [Dineshkarthik/telegram_media_downloader#117]
Hi,

I've installed your app according to the readme and configured it via the config file. I can start the app, enter my phone number and the confirmation code afterwards, but as soon as I press Enter after the code, I only get:

`pyrogram.errors.exceptions.not_acceptable_406.NotAcceptable: [406 Not Acceptable]: [406 UPDATE_APP_TO_LOGIN] (caused by "auth.SignIn")`

error in full:

```
INFO:pyrogram.session.session:PingTask started
The confirmation code has been sent via Telegram app
Enter confirmation code: xxxxx
INFO:pyrogram.session.session:PingTask stopped
INFO:pyrogram.session.session:NextSaltTask stopped
INFO:pyrogram.connection.connection:Disconnected
INFO:pyrogram.session.session:NetworkTask stopped
INFO:pyrogram.session.session:Session stopped
Traceback (most recent call last):
  File "/home/username/telegram_media_downloader/media_downloader.py", line 358, in <module>
    main()
  File "/home/username/telegram_media_downloader/media_downloader.py", line 342, in main
    updated_config = asyncio.get_event_loop().run_until_complete(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/username/telegram_media_downloader/media_downloader.py", line 298, in begin_import
    await client.start()
  File "/home/username/.local/lib/python3.9/site-packages/pyrogram/methods/utilities/start.py", line 57, in start
    await self.authorize()
  File "/home/username/.local/lib/python3.9/site-packages/pyrogram/client.py", line 328, in authorize
    signed_in = await self.sign_in(self.phone_number, sent_code.phone_code_hash, self.phone_code)
  File "/home/username/.local/lib/python3.9/site-packages/pyrogram/methods/auth/sign_in.py", line 61, in sign_in
    r = await self.send(
  File "/home/username/.local/lib/python3.9/site-packages/pyrogram/methods/advanced/send.py", line 77, in send
    r = await self.session.send(
  File "/home/username/.local/lib/python3.9/site-packages/pyrogram/session/session.py", line 425, in send
    return await self._send(data, timeout=timeout)
  File "/home/username/.local/lib/python3.9/site-packages/pyrogram/session/session.py", line 395, in _send
    RPCError.raise_it(result, type(data))
  File "/home/username/.local/lib/python3.9/site-packages/pyrogram/errors/rpc_error.py", line 68, in raise_it
    raise getattr(
pyrogram.errors.exceptions.not_acceptable_406.NotAcceptable: [406 Not Acceptable]: [406 UPDATE_APP_TO_LOGIN] (caused by "auth.SignIn")
```

OS: Debian 11 stable.

Thanks in advance!

**Comment by thehenil** [comment]
I was having the same issue, just update your telethon, pyrogram to the latest version. And your issue will get resolved.

Thanks,
HENiL

**Comment by thehenil** [comment]
`pip pyrogram --upgrade`
`pip telethon --upgrade`

**Comment by thehenil** [comment]
`pip install --upgrade telethon`
`pip install --upgrade pyrogram`

**Comment by Wurzelmann** [comment]
Thank you, issue no longer relevant, since not using Telegram anymore, sorry for the inconvenience.
