### ISSUE TITLE
I have errors while downloading through a Private Channel

### ISSUE THREAD

**Issue by usapanglashing** [Dineshkarthik/telegram_media_downloader#234]
Traceback (most recent call last):
  File "D:\TG\TGMD\media_downloader.py", line 380, in <module>
    main()
  File "D:\TG\TGMD\media_downloader.py", line 364, in main
    updated_config = asyncio.get_event_loop().run_until_complete(
  File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "D:\TG\TGMD\media_downloader.py", line 315, in begin_import
    messages_iter = client.iter_history(
AttributeError: 'Client' object has no attribute 'iter_history'

**Comment by Dineshkarthik** [comment]
The Pyrogram version you installed seems to be >=2.0 where are the version given in requirements.txt is `Pyrogram==1.4.12` install the correct version.
