### ISSUE TITLE
400 CHANNEL_INVALID

### ISSUE THREAD

**Issue by Bazzu85** [Dineshkarthik/telegram_media_downloader#247]
**Describe the bug**
Running media_downloader.py give the error

```
[19:20:38] Telegram Media Downloader v1.5.1,                                                                 meta.py:20
           Copyright (C) 2019 Dineshkarthik <https://github.com/Dineshkarthik>
           Licensed under the terms of the MIT License                                                       meta.py:23

[19:20:38] INFO     Device: CPython 3.10.4 - Telegram Media Downloader 1.5.1                                 meta.py:24
           INFO     System: Windows 10 (EN)                                                                  meta.py:25
n:\Telegram Media Downloader\media_downloader.py:364: DeprecationWarning: There is no current event loop
  updated_config = asyncio.get_event_loop().run_until_complete(
[19:20:39] INFO     Connecting...                                                                      connection.py:56
           INFO     Connected! Production DC4 - IPv4 - TCPAbridgedO                                    connection.py:63
           INFO     NetworkTask started                                                                  session.py:272
           INFO     Time synced: 2022-06-07 17:20:39.932761 UTC                                            msg_id.py:45
           INFO     Session initialized: Layer 139                                                       session.py:131
           INFO     Device: CPython 3.10.4 - Pyrogram 1.4.12                                             session.py:132
           INFO     System: Windows 10 (EN)                                                              session.py:133
           INFO     Session started                                                                      session.py:148
           INFO     PingTask started                                                                     session.py:250
           INFO     Started 16 HandlerTasks                                                           dispatcher.py:136
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\pyrogram\methods\advanced\resolve_peer.py", line 60, in resolve_peer
    return await self.storage.get_peer_by_id(peer_id)
  File "C:\Python310\lib\site-packages\pyrogram\storage\sqlite_storage.py", line 147, in get_peer_by_id
    raise KeyError(f"ID not found: {peer_id}")
KeyError: 'ID not found: -1001313958729'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "n:\Telegram Media Downloader\media_downloader.py", line 380, in <module>
    main()
  File "n:\Telegram Media Downloader\media_downloader.py", line 364, in main
    updated_config = asyncio.get_event_loop().run_until_complete(
  File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "n:\Telegram Media Downloader\media_downloader.py", line 331, in begin_import
    async for message in messages_iter:  # type: ignore
  File "C:\Python310\lib\site-packages\pyrogram\methods\messages\iter_history.py", line 79, in iter_history
    messages = await self.get_history(
  File "C:\Python310\lib\site-packages\pyrogram\methods\messages\get_history.py", line 90, in get_history
    peer=await self.resolve_peer(chat_id),
  File "C:\Python310\lib\site-packages\pyrogram\methods\advanced\resolve_peer.py", line 109, in resolve_peer
    await self.send(
  File "C:\Python310\lib\site-packages\pyrogram\methods\advanced\send.py", line 77, in send
    r = await self.session.send(
  File "C:\Python310\lib\site-packages\pyrogram\session\session.py", line 362, in send
    return await self._send(data, timeout=timeout)
  File "C:\Python310\lib\site-packages\pyrogram\session\session.py", line 332, in _send
    RPCError.raise_it(result, type(data))
  File "C:\Python310\lib\site-packages\pyrogram\errors\rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ChannelInvalid: Telegram says: [400 CHANNEL_INVALID] - The channel parameter is invalid (caused by "channels.GetChannels")
```

**To Reproduce**
use this yaml
```
chat_id: -1001313958729
last_read_message_id: 0
ids_to_retry: []
media_types:
- audio
- photo
- video
- document
- voice
- video_note
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
```

**Python Version**
Python: 10

**OS:**
The OS and its version: Windows 10 Pro
**Logs**
see above
**Additional context**

**Comment by Dineshkarthik** [comment]
HI,
The channel id is not correct or you don't have access to the channel id you are trying to download from.

**Comment by Bazzu85** [comment]
> HI, The channel id is not correct or you don't have access to the channel id you are trying to download from.

Hi,
here's the IDbot screen:

![image](https://user-images.githubusercontent.com/7345587/172713973-fa2592a2-bd0e-4d1d-8895-8d5deddbe900.png)

And from telegram app I can access the Channel.

I tried to create a new public Channel @DownloadTester (try to join you too)
![image](https://user-images.githubusercontent.com/7345587/172714318-8b0afe36-a14f-4c20-a0d7-4eaf646698e7.png)

and this also doesn't work ..

**Comment by Dineshkarthik** [comment]
If you already have the channel name - then use it instead of the channel id. OnePieceAScN1

**Comment by Bazzu85** [comment]
> If you already have the channel name - then use it instead of the channel id. OnePieceAScN1

With this yaml

```
api_hash: 95ab2da3ddcefe23b758e60077934831
api_id: 9275059
chat_id: OnePieceAScN1
last_read_message_id: 0
ids_to_retry: []
media_types:
- audio
- photo
- video
- document
- voice
- video_note
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
```

Hi have the error:
```
[01:07:53] Telegram Media Downloader v1.5.1,                                                                 meta.py:20
           Copyright (C) 2019 Dineshkarthik <https://github.com/Dineshkarthik>
           Licensed under the terms of the MIT License                                                       meta.py:23

[01:07:53] INFO     Device: CPython 3.10.4 - Telegram Media Downloader 1.5.1                                 meta.py:24
           INFO     System: Windows 10 (EN)                                                                  meta.py:25
n:\Telegram Media Downloader\media_downloader.py:364: DeprecationWarning: There is no current event loop
  updated_config = asyncio.get_event_loop().run_until_complete(
[01:07:54] INFO     Connecting...                                                                      connection.py:56
           INFO     Connected! Production DC4 - IPv4 - TCPAbridgedO                                    connection.py:63
           INFO     NetworkTask started                                                                  session.py:272
           INFO     Time synced: 2022-06-08 23:07:55.110759 UTC                                            msg_id.py:45
           INFO     Session initialized: Layer 139                                                       session.py:131
           INFO     Device: CPython 3.10.4 - Pyrogram 1.4.12                                             session.py:132
           INFO     System: Windows 10 (EN)                                                              session.py:133
           INFO     Session started                                                                      session.py:148
           INFO     PingTask started                                                                     session.py:250
           INFO     Started 16 HandlerTasks                                                           dispatcher.py:136
Traceback (most recent call last):
  File "n:\Telegram Media Downloader\media_downloader.py", line 380, in <module>
    main()
  File "n:\Telegram Media Downloader\media_downloader.py", line 364, in main
    updated_config = asyncio.get_event_loop().run_until_complete(
  File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "n:\Telegram Media Downloader\media_downloader.py", line 331, in begin_import
    async for message in messages_iter:  # type: ignore
  File "C:\Python310\lib\site-packages\pyrogram\methods\messages\iter_history.py", line 79, in iter_history
    messages = await self.get_history(
  File "C:\Python310\lib\site-packages\pyrogram\methods\messages\get_history.py", line 88, in get_history
    await self.send(
  File "C:\Python310\lib\site-packages\pyrogram\methods\advanced\send.py", line 77, in send
    r = await self.session.send(
  File "C:\Python310\lib\site-packages\pyrogram\session\session.py", line 362, in send
    return await self._send(data, timeout=timeout)
  File "C:\Python310\lib\site-packages\pyrogram\session\session.py", line 332, in _send
    RPCError.raise_it(result, type(data))
  File "C:\Python310\lib\site-packages\pyrogram\errors\rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.BotMethodInvalid: Telegram says: [400 BOT_METHOD_INVALID] - The method can't be used by bots (caused by "messages.GetHistory")
```

**Comment by Dineshkarthik** [comment]
It seems you are using a bot token  as Api key and hash key you need to use user api key and hash key.

**Getting your API Keys**: The very first step requires you to obtain a valid Telegram API key (API id/hash pair):

Visit https://my.telegram.org/apps and log in with your Telegram Account.
Fill out the form to register a new Telegram application.
Done! The API key consists of two parts: api_id and api_hash.

**Comment by TianLanSky** [comment]
I meet the same problem.
Did U resolved it?
