### ISSUE TITLE
New Error on version 2.0.1

### ISSUE THREAD

**Issue by JustGuardian** [Dineshkarthik/telegram_media_downloader#289]
Just updated to version 2.0.1 and I got this, I already have done `pip install -r requirements.txt`
```
Traceback (most recent call last):
  File "C:\Users\user\telegram_media_downloader-2.0.1\media_downloader.py", line 375, in <module>
    main()
  File "C:\Users\user\telegram_media_downloader-2.0.1\media_downloader.py", line 359, in main
    updated_config = asyncio.get_event_loop().run_until_complete(
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\user\telegram_media_downloader-2.0.1\media_downloader.py", line 312, in begin_import
    messages_iter = client.get_chat_history(
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pyrogram\sync.py", line 53, in async_to_sync_wrap
    coroutine = function(*args, **kwargs)
TypeError: get_chat_history() got an unexpected keyword argument 'reverse'
```

**Comment by Dineshkarthik** [comment]
Can you try uninstalling pyrogam and then reinstall? 
```sh
pip uninstall Pyrogram
pip install -r requirements.txt
```

**Comment by JustGuardian** [comment]
Working now, thanks another time!
