### ISSUE TITLE
bug-for 2.0.1

### ISSUE THREAD

**Issue by icefins** [Dineshkarthik/telegram_media_downloader#291]
Traceback (most recent call last):
  File "/telegram_media_downloader/media_downloader.py", line 375, in <module>
    main()
  File "/telegram_media_downloader/media_downloader.py", line 359, in main
    updated_config = asyncio.get_event_loop().run_until_complete(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/telegram_media_downloader/media_downloader.py", line 312, in begin_import
    messages_iter = client.get_chat_history(
  File "/usr/local/lib/python3.9/site-packages/pyrogram/sync.py", line 53, in async_to_sync_wrap
    coroutine = function(*args, **kwargs)
TypeError: get_chat_history() got an unexpected keyword argument 'reverse'

**Comment by Dineshkarthik** [comment]
As mentioned in the [release note](https://github.com/Dineshkarthik/telegram_media_downloader/releases/tag/v2.0.1) uninstall and reinstall package. 
```sh
pip uninstall Pyrogram
make install
```
