### ISSUE TITLE
in send raise TimeoutError ,Unable to download more files!

### ISSUE THREAD

**Issue by XHXJ** [Dineshkarthik/telegram_media_downloader#299]
**Describe the bug**
Most of the files reported this error when I downloaded it, may I ask how to solve it? Seems to be a connection timeout error.

 My idea is can connection timeout be set and where?

Because I found that some of my video downloads took some time to connect before they started downloading, the default wait time seemed too short.

 
 

**To Reproduce**
```yaml
chat_id: telegram_chat_id
last_read_message_id: 0
media_types:
- audio
- photo
- video
- document
- voice
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
```

**Python Version**
Python: 3.9.7

**OS:**
Ubuntu 18.04.6

**Logs**
```
           INFO     Media downloaded - /www/wwwroot/telegram_media_downloader-2.0.1/telegram_media_downloader/video/X269.mov                                     media_downloader.py:195
           ERROR                                                                                                                                                           client.py:979
                    Traceback (most recent call last):                                                                                                                                  
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/client.py", line 848,               
                    in get_file                                                                                                                                                         
                        r = await session.invoke(                                                                                                                                       
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/session/session.py",                
                    line 381, in invoke                                                                                                                                                 
                        return await self.invoke(query, retries - 1, timeout)                                                                                                           
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/session/session.py",                
                    line 381, in invoke                                                                                                                                                 
                        return await self.invoke(query, retries - 1, timeout)                                                                                                           
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/session/session.py",                
                    line 381, in invoke                                                                                                                                                 
                        return await self.invoke(query, retries - 1, timeout)                                                                                                           
                      [Previous line repeated 2 more times]                                                                                                                             
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/session/session.py",                
                    line 374, in invoke                                                                                                                                                 
                        raise e from None                                                                                                                                               
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/session/session.py",                
                    line 361, in invoke                                                                                                                                                 
                        return await self.send(query, timeout=timeout)                                                                                                                  
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/session/session.py",                
                    line 326, in send                                                                                                                                                   
                        raise TimeoutError                                                                                                                                              
                    TimeoutError                                                                                                                                                        
           INFO     Media downloaded - /www/wwwroot/telegram_media_downloader-2.0.1/telegram_media_downloader/video/X271 (1).mp4                                 media_downloader.py:195
           ERROR                                                                                                                                                           client.py:979
                    Traceback (most recent call last):                                                                                                                                  
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/client.py", line 848,               
                    in get_file                                                                                                                                                         
                        r = await session.invoke(                                                                                                                                       
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/session/session.py",                
                    line 381, in invoke                                                                                                                                                 
                        return await self.invoke(query, retries - 1, timeout)                                                                                                           
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/session/session.py",                
                    line 381, in invoke                                                                                                                                                 
                        return await self.invoke(query, retries - 1, timeout)                                                                                                           
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/session/session.py",                
                    line 381, in invoke                                                                                                                                                 
                        return await self.invoke(query, retries - 1, timeout)                                                                                                           
                      [Previous line repeated 2 more times]                                                                                                                             
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/session/session.py",                
                    line 374, in invoke                                                                                                                                                 
                        raise e from None                                                                                                                                               
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/session/session.py",                
                    line 361, in invoke                                                                                                                                                 
                        return await self.send(query, timeout=timeout)                                                                                                                  
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/session/session.py",                
                    line 326, in send                                                                                                                                                   
                        raise TimeoutError                                                                                                                                              
                    TimeoutError                                                                                                                                                        
           INFO     Media downloaded - /www/wwwroot/telegram_media_downloader-2.0.1/telegram_media_downloader/video/X278 (1).mp4                                 media_downloader.py:195
           ERROR                                                                                                                                                           client.py:979
                    Traceback (most recent call last):                                                                                                                                  
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/client.py", line 848,               
                    in get_file                                                                                                                                                         
                        r = await session.invoke(                                                                                                                                       
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/session/session.py",                
                    line 381, in invoke                                                                                                                                                 
                        return await self.invoke(query, retries - 1, timeout)                                                                                                           
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/session/session.py",                
                    line 381, in invoke                                                                                                                                                 
                        return await self.invoke(query, retries - 1, timeout)                                                                                                           
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/session/session.py",                
                    line 381, in invoke                                                                                                                                                 
                        return await self.invoke(query, retries - 1, timeout)                                                                                                           
                      [Previous line repeated 2 more times]                                                                                                                             
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/session/session.py",                
                    line 374, in invoke                                                                                                                                                 
                        raise e from None                                                                                                                                               
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/session/session.py",                
                    line 361, in invoke                                                                                                                                                 
                        return await self.send(query, timeout=timeout)                                                                                                                  
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/session/session.py",                
                    line 326, in send                                                                                                                                                   
                        raise TimeoutError                                                                                                                                              
                    TimeoutError                                                                                                                                                        
           INFO     Media downloaded - /www/wwwroot/telegram_media_downloader-2.0.1/telegram_media_downloader/video/X279 (1).mp4                                 media_downloader.py:195
           ERROR                                                                                                                                                           client.py:979
                    Traceback (most recent call last):                                                                                                                                  
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/client.py", line 848,               
                    in get_file                                                                                                                                                         
                        r = await session.invoke(                                                                                                                                       
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/session/session.py",                
                    line 381, in invoke                                                                                                                                                 
                        return await self.invoke(query, retries - 1, timeout)                                                                                                           
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/session/session.py",                
                    line 381, in invoke                                                                                                                                                 
                        return await self.invoke(query, retries - 1, timeout)                                                                                                           
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/session/session.py",                
                    line 381, in invoke                                                                                                                                                 
                        return await self.invoke(query, retries - 1, timeout)                                                                                                           
                      [Previous line repeated 2 more times]                                                                                                                             
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/session/session.py",                
                    line 374, in invoke                                                                                                                                                 
                        raise e from None                                                                                                                                               
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/session/session.py",                
                    line 361, in invoke                                                                                                                                                 
                        return await self.send(query, timeout=timeout)                                                                                                                  
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/session/session.py",                
                    line 326, in send                                                                                                                                                   
                        raise TimeoutError                                                                                                                                              
                    TimeoutError                                                                                                                                                        
           INFO     Media downloaded - /www/wwwroot/telegram_media_downloader-2.0.1/telegram_media_downloader/video/X281.mp4                                     media_downloader.py:195
           ERROR                                                                                                                                                           client.py:979
                    Traceback (most recent call last):                                                                                                                                  
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/client.py", line 848,               
                    in get_file                                                                                                                                                         
                        r = await session.invoke(                                                                                                                                       
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/session/session.py",                
                    line 381, in invoke                                                                                                                                                 
                        return await self.invoke(query, retries - 1, timeout)                                                                                                           
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/session/session.py",                
                    line 381, in invoke                                                                                                                                                 
                        return await self.invoke(query, retries - 1, timeout)                                                                                                           
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/session/session.py",                
                    line 381, in invoke                                                                                                                                                 
                        return await self.invoke(query, retries - 1, timeout)                                                                                                           
                      [Previous line repeated 2 more times]                                                                                                                             
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/session/session.py",                
                    line 374, in invoke                                                                                                                                                 
                        raise e from None                                                                                                                                               
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/session/session.py",                
                    line 361, in invoke                                                                                                                                                 
                        return await self.send(query, timeout=timeout)                                                                                                                  
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/session/session.py",                
                    line 326, in send                                                                                                                                                   
                        raise TimeoutError                                                                                                                                              
                    TimeoutError                                                                                                                                                        
           INFO     Media downloaded - /www/wwwroot/telegram_media_downloader-2.0.1/telegram_media_downloader/video/X283.mp4                                     media_downloader.py:195
           ERROR                                                                                                                                                           client.py:979
                    Traceback (most recent call last):                                                                                                                                  
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/client.py", line 848,               
                    in get_file                                                                                                                                                         
                        r = await session.invoke(                                                                                                                                       
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/session/session.py",                
                    line 381, in invoke                                                                                                                                                 
                        return await self.invoke(query, retries - 1, timeout)                                                                                                           
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/session/session.py",                
                    line 381, in invoke                                                                                                                                                 
                        return await self.invoke(query, retries - 1, timeout)                                                                                                           
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/session/session.py",                
                    line 381, in invoke                                                                                                                                                 
                        return await self.invoke(query, retries - 1, timeout)                                                                                                           
                      [Previous line repeated 2 more times]                                                                                                                             
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/session/session.py",                
                    line 374, in invoke                                                                                                                                                 
                        raise e from None                                                                                                                                               
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/session/session.py",                
                    line 361, in invoke                                                                                                                                                 
                        return await self.send(query, timeout=timeout)                                                                                                                  
                      File "/www/wwwroot/telegram_media_downloader-2.0.1/28281fa6acfdcf0587ec679296f517a0_venv/lib/python3.9/site-packages/pyrogram/session/session.py",                
                    line 326, in send                                                                                                                                                   
                        raise TimeoutError                                                                                                                                              
                    TimeoutError          
```

**Comment by Dineshkarthik** [comment]
Made some changes to the forked Pyrogram can you try uninstalling and installing again.
```sh
pip uninstall Pyrogram
make install
```

**Comment by XHXJ** [comment]
> 对分叉的Pyrogram进行了一些更改，您可以尝试卸载并重新安装。
> 
> ```shell
> pip uninstall Pyrogram
> make install
> ```

I downgraded my Python version (3.7.9), but the problem remains and the dependency has been reinstalled

**Comment by Dineshkarthik** [comment]
superseded by #300

**Comment by nongtor01** [comment]
I'm having the same problem on windows. 
how should i fix it?
