### ISSUE TITLE
Typeerror

### ISSUE THREAD

**Issue by 99215194** [Dineshkarthik/telegram_media_downloader#303]
Traceback (most recent call last):
  File "E:\Hell\telegram_media_downloader-2.0.2\media_downloader.py", line 376, in <module>
    main()
  File "E:\Hell\telegram_media_downloader-2.0.2\media_downloader.py", line 360, in main
    updated_config = asyncio.get_event_loop().run_until_complete(
  File "C:\Users\Neo\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "E:\Hell\telegram_media_downloader-2.0.2\media_downloader.py", line 313, in begin_import
    messages_iter = client.get_chat_history(
  File "C:\Users\Neo\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\sync.py", line 53, in async_to_sync_wrap
    coroutine = function(*args, **kwargs)
TypeError: GetChatHistory.get_chat_history() got an unexpected keyword argument 'reverse'

**Comment by Dineshkarthik** [comment]
As mentioned in the release notes, re-install/update your dependence packages.
```sh
pip install -r requirements.txt
```
