### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by Seven-QISi** [Dineshkarthik/telegram_media_downloader#315]
[18:20:44] Telegram Media Downloader v2.0.2,                                                                                                                                                           meta.py:18
           Copyright (C) 2019 Dineshkarthik <https://github.com/Dineshkarthik>
           Licensed under the terms of the MIT License                                                                                                                                                 meta.py:21

[18:20:44] INFO     Device: CPython 3.10.5 - Telegram Media Downloader 2.0.2                                                                                                                           meta.py:22
           INFO     System: Windows 10 (EN)                                                                                                                                                            meta.py:23
\\DS3615xs\Color\Telegram\telegram_media_downloader-2.0.2\media_downloader.py:360: DeprecationWarning: There is no current event loop
  updated_config = asyncio.get_event_loop().run_until_complete(
           INFO     Start creating a new auth key on DC2                                                                                                                                               auth.py:82
           INFO     Using proxy 127.0.0.1                                                                                                                                                               tcp.py:72
           INFO     Connecting...                                                                                                                                                                connection.py:56
           INFO     Connected! Production DC2 - IPv4 - TCPAbridgedO                                                                                                                              connection.py:63
[18:20:46] INFO     Disconnected                                                                                                                                                                 connection.py:77
           INFO     Start creating a new auth key on DC2                                                                                                                                               auth.py:82
           INFO     Using proxy 127.0.0.1                                                                                                                                                               tcp.py:72
           INFO     Connecting...                                                                                                                                                                connection.py:56
           INFO     Connected! Production DC2 - IPv4 - TCPAbridgedO                                                                                                                              connection.py:63
[18:20:47] INFO     Disconnected                                                                                                                                                                 connection.py:77
           INFO     Start creating a new auth key on DC2                                                                                                                                               auth.py:82
           INFO     Using proxy 127.0.0.1                                                                                                                                                               tcp.py:72
           INFO     Connecting...                                                                                                                                                                connection.py:56
           INFO     Connected! Production DC2 - IPv4 - TCPAbridgedO                                                                                                                              connection.py:63
[18:20:48] INFO     Disconnected                                                                                                                                                                 connection.py:77
           INFO     Start creating a new auth key on DC2                                                                                                                                               auth.py:82
           INFO     Using proxy 127.0.0.1                                                                                                                                                               tcp.py:72
           INFO     Connecting...                                                                                                                                                                connection.py:56
           INFO     Connected! Production DC2 - IPv4 - TCPAbridgedO                                                                                                                              connection.py:63
[18:20:49] INFO     Disconnected                                                                                                                                                                 connection.py:77
           INFO     Start creating a new auth key on DC2                                                                                                                                               auth.py:82
           INFO     Using proxy 127.0.0.1                                                                                                                                                               tcp.py:72
           INFO     Connecting...                                                                                                                                                                connection.py:56
           INFO     Connected! Production DC2 - IPv4 - TCPAbridgedO                                                                                                                              connection.py:63
[18:21:00] INFO     Disconnected                                                                                                                                                                 connection.py:77
           INFO     Start creating a new auth key on DC2                                                                                                                                               auth.py:82
           INFO     Using proxy 127.0.0.1                                                                                                                                                               tcp.py:72
           INFO     Connecting...                                                                                                                                                                connection.py:56
           INFO     Connected! Production DC2 - IPv4 - TCPAbridgedO                                                                                                                              connection.py:63
           INFO     Disconnected                                                                                                                                                                 connection.py:77
Traceback (most recent call last):
  File "\\DS3615xs\Color\Telegram\telegram_media_downloader-2.0.2\media_downloader.py", line 376, in <module>
    main()
  File "\\DS3615xs\Color\Telegram\telegram_media_downloader-2.0.2\media_downloader.py", line 360, in main
    updated_config = asyncio.get_event_loop().run_until_complete(
  File "C:\Users\jingnan\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "\\DS3615xs\Color\Telegram\telegram_media_downloader-2.0.2\media_downloader.py", line 311, in begin_import
    await client.start()
  File "C:\Users\jingnan\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\methods\utilities\start.py", line 58, in start
    is_authorized = await self.connect()
  File "C:\Users\jingnan\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\methods\auth\connect.py", line 40, in connect
    await self.load_session()
  File "C:\Users\jingnan\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\client.py", line 584, in load_session
    await Auth(
  File "C:\Users\jingnan\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\session\auth.py", line 254, in create
    raise e
  File "C:\Users\jingnan\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\session\auth.py", line 89, in create
    res_pq = await self.invoke(raw.functions.ReqPqMulti(nonce=nonce))
  File "C:\Users\jingnan\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\session\auth.py", line 67, in invoke
    return self.unpack(response)
  File "C:\Users\jingnan\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\session\auth.py", line 60, in unpack
    return TLObject.read(b)
  File "C:\Users\jingnan\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\raw\core\tl_object.py", line 33, in read
    return cast(TLObject, objects[int.from_bytes(b.read(4), "little")]).read(b, *args)
KeyError: 0

**Comment by wylloong** [comment]
Ditto.

[19:21:21] INFO     Disconnected                                                                                                                                                            connection.py:77
           INFO     NetworkTask stopped                                                                                                                                                       session.py:287
           INFO     Session stopped                                                                                                                                                           session.py:174
           INFO     Using proxy 127.0.0.1                                                                                                                                                          tcp.py:72
           INFO     Connecting...                                                                                                                                                           connection.py:56
           INFO     Connected! Production DC2 - IPv4 - TCPAbridgedO                                                                                                                         connection.py:63
           INFO     NetworkTask started                                                                                                                                                       session.py:271
[19:21:22] INFO     Disconnected                                                                                                                                                            connection.py:77
           INFO     NetworkTask stopped                                                                                                                                                       session.py:287
           INFO     Session stopped                                                                                                                                                           session.py:174
           INFO     Using proxy 127.0.0.1                                                                                                                                                          tcp.py:72
           INFO     Connecting...                                                                                                                                                           connection.py:56
           INFO     Connected! Production DC2 - IPv4 - TCPAbridgedO                                                                                                                         connection.py:63
           INFO     NetworkTask started                                                                                                                                                       session.py:271
[19:21:23] INFO     Disconnected                                                                                                                                                            connection.py:77
           INFO     NetworkTask stopped                                                                                                                                                       session.py:287
           INFO     Session stopped                                                                                                                                                           session.py:174
           INFO     Using proxy 127.0.0.1                                                                                                                                                          tcp.py:72
           INFO     Connecting...                                                                                                                                                           connection.py:56
           INFO     Connected! Production DC2 - IPv4 - TCPAbridgedO                                                                                                                         connection.py:63
           INFO     NetworkTask started                                                                                                                                                       session.py:271
[19:21:24] INFO     Disconnected                                                                                                                                                            connection.py:77
           INFO     NetworkTask stopped                                                                                                                                                       session.py:287
