### ISSUE TITLE
运行代码出错

### ISSUE THREAD

**Issue by ZhaoRongBoBo** [Dineshkarthik/telegram_media_downloader#322]
Traceback (most recent call last):
  File "D:/pythonProject/telegram_media_downloader-2.0.2/media_downloader.py", line 376, in <module>
    main()
  File "D:/pythonProject/telegram_media_downloader-2.0.2/media_downloader.py", line 360, in main
    updated_config = asyncio.get_event_loop().run_until_complete(
  File "D:\Program Files (x86)\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "D:/pythonProject/telegram_media_downloader-2.0.2/media_downloader.py", line 311, in begin_import
    await client.start()
  File "D:\Program Files (x86)\Python\Python38\lib\site-packages\pyrogram\methods\utilities\start.py", line 58, in start
    is_authorized = await self.connect()
  File "D:\Program Files (x86)\Python\Python38\lib\site-packages\pyrogram\methods\auth\connect.py", line 40, in connect
    await self.load_session()
  File "D:\Program Files (x86)\Python\Python38\lib\site-packages\pyrogram\client.py", line 584, in load_session
    await Auth(
  File "D:\Program Files (x86)\Python\Python38\lib\site-packages\pyrogram\session\auth.py", line 261, in create
    self.connection.close()
  File "D:\Program Files (x86)\Python\Python38\lib\site-packages\pyrogram\connection\connection.py", line 76, in close
    self.protocol.close()
AttributeError: 'NoneType' object has no attribute 'close'

**Comment by iamtwvl** [comment]
I have the same trouble :(
