### ISSUE TITLE
down erro

### ISSUE THREAD

**Issue by loeveo** [Dineshkarthik/telegram_media_downloader#33]
ERROR:pyrogram.client.client:
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyrogram/client/client.py", line 2008, in get_file
    r = await session.send(
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyrogram/session/session.py", line 451, in send
    return await self.send(data, retries - 1, timeout)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyrogram/session/session.py", line 451, in send
    return await self.send(data, retries - 1, timeout)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyrogram/session/session.py", line 451, in send
    return await self.send(data, retries - 1, timeout)
  [Previous line repeated 2 more times]
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyrogram/session/session.py", line 442, in send
    raise e from None
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyrogram/session/session.py", line 429, in send
    return await self._send(data, timeout=timeout)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyrogram/session/session.py", line 394, in _send
    raise TimeoutError
TimeoutError
ERROR:pyrogram.client.client:
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyrogram/client/client.py", line 2008, in get_file
    r = await session.send(
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyrogram/session/session.py", line 451, in send
    return await self.send(data, retries - 1, timeout)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyrogram/session/session.py", line 451, in send
    return await self.send(data, retries - 1, timeout)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyrogram/session/session.py", line 451, in send
    return await self.send(data, retries - 1, timeout)
  [Previous line repeated 2 more times]
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyrogram/session/session.py", line 442, in send
    raise e from None
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyrogram/session/session.py", line 429, in send
    return await self._send(data, timeout=timeout)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyrogram/session/session.py", line 394, in _send
    raise TimeoutError
TimeoutError
ERROR:pyrogram.client.client:
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyrogram/client/client.py", line 2008, in get_file
    r = await session.send(
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyrogram/session/session.py", line 451, in send
    return await self.send(data, retries - 1, timeout)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyrogram/session/session.py", line 451, in send
    return await self.send(data, retries - 1, timeout)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyrogram/session/session.py", line 451, in send
    return await self.send(data, retries - 1, timeout)
  [Previous line repeated 2 more times]
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyrogram/session/session.py", line 442, in send
    raise e from None
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyrogram/session/session.py", line 429, in send
    return await self._send(data, timeout=timeout)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyrogram/session/session.py", line 394, in _send
    raise TimeoutError
TimeoutError
INFO:__main__:Media downloaded - None
INFO:__main__:Media downloaded - None
Traceback (most recent call last):
  File "media_downloader.py", line 232, in <module>
    updated_config = asyncio.get_event_loop().run_until_complete(
  File "/data/data/com.termux/files/usr/lib/python3.8/asyncio/base_events.py", line 612, in run_until_complete
    return future.result()
  File "media_downloader.py", line 206, in begin_import
    last_read_message_id = await process_messages(
  File "media_downloader.py", line 175, in process_messages
    message_ids = await asyncio.gather(
  File "media_downloader.py", line 134, in download_media
    download_path = manage_duplicate_file(download_path)
  File "/storage/emulated/0/ADM/nsfw/utils/file_management.py", line 37, in manage_duplicate_file
    posix_path = pathlib.Path(file_path)
  File "/data/data/com.termux/files/usr/lib/python3.8/pathlib.py", line 1035, in __new__
    self = cls._from_parts(args, init=False)
  File "/data/data/com.termux/files/usr/lib/python3.8/pathlib.py", line 676, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/data/data/com.termux/files/usr/lib/python3.8/pathlib.py", line 660, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by Dineshkarthik** [comment]
Hi this seems to be a timeout error, can you try re-running the script and check.

**Comment by loeveo** [comment]
> 您好，这似乎是超时错误，您可以尝试重新运行脚本并进行检查吗？

Oh, okay, thanks. But can I trouble the author to think about it, are there other functional requirements I mentioned?  Especially the ID number of the downloaded file is written in real time. Otherwise, it cannot be continued under such a sudden interruption or manual stop.

**Comment by Dineshkarthik** [comment]
yeah, I am planning to work on those other feature requests soon.

**Comment by loeveo** [comment]
> yeah, I am planning to work on those other feature requests soon.

Traceback (most recent call last):
  File "media_downloader.py", line 233, in <module>
    begin_import(config, pagination_limit=100)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "media_downloader.py", line 210, in begin_import
    config["file_formats"],
  File "media_downloader.py", line 178, in process_messages
    for message in messages
  File "media_downloader.py", line 134, in download_media
    download_path = manage_duplicate_file(download_path)
  File "/home/telegram_media_downloader/utils/file_management.py", line 41, in manage_duplicate_file
    old_files.remove(file_path)
ValueError: list.remove(x): x not in list

**Comment by Dineshkarthik** [comment]
Can you share the chat-id if it is a public one? Would like to have some sample data to replicate the above.

**Comment by loeveo** [comment]
> Can you share the chat-id if it is a public one? Would like to have some sample data to replicate the above.

It doesn’t seem to be the cause of the channel, because several of my channels are like this. It should be because there are too many downloads.

**Comment by Dineshkarthik** [comment]
Of course, it is has nothing to do with the channel. I am trying to replicate the issue hence needed the channel-id

**Comment by loeveo** [comment]
> Of course, it is has nothing to do with the channel. I am trying to replicate the issue hence needed the channel-id

@dedao_eBook

**Comment by loeveo** [comment]
> Of course, it is has nothing to do with the channel. I am trying to replicate the issue hence needed the channel-id

@dedao_eBook

**Comment by Dineshkarthik** [comment]
Unable to replicate this issue. Are you still facing this issue?
