### ISSUE TITLE
SQLITE3 Databese Locked

### ISSUE THREAD

**Issue by silente** [Dineshkarthik/telegram_media_downloader#35]
`Traceback (most recent call last):
  File "media_downloader.py", line 233, in <module>
    begin_import(config, pagination_limit=100)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "media_downloader.py", line 193, in begin_import
    await client.start()
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/client/client.py", line 833, in start
    is_authorized = await self.connect()
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/client/client.py", line 283, in connect
    await self.load_session()
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/client/client.py", line 1505, in load_session
    self.storage.open()
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/client/storage/file_storage.py", line 112, in open
    self.update()
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/client/storage/file_storage.py", line 79, in update
    self.version(version)
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/client/storage/sqlite_storage.py", line 183, in version
    (value,)
sqlite3.OperationalError: database is locked`

**Comment by Dineshkarthik** [comment]
Delete `media_downloader.session` file and try again
