### ISSUE TITLE
The msg_id is too low, the client time has to be synchronized.

### ISSUE THREAD

**Issue by liuzhiyi0531** [Dineshkarthik/telegram_media_downloader#447]
It used to work fine, but on this occasion an error was reported when running the script
If reconfigure the script environment, It can run it once, then run it again with the same error

**To Reproduce**
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
ids_to_retry: []
last_read_message_id: 2418
media_types:
- photo
- video

**Python Version**
Python: 3.10.11

**OS:**
WIN10

**Logs**
[10:10:44] INFO     Device: CPython 3.10.11 - Telegram Media Downloader 2.0.2                                meta.py:22
           INFO     System: Windows 10 (EN)                                                                  meta.py:23
[10:10:46] INFO     Connecting...                                                                      connection.py:56
           INFO     Connected! Production DC1 - IPv4 - TCPAbridgedO                                    connection.py:63
           INFO     NetworkTask started                                                                  session.py:271
[10:10:47] INFO     Time synced: 2023-06-15 18:10:47.672824 UTC                                            msg_id.py:45
           INFO     Disconnected                                                                       connection.py:77
           INFO     NetworkTask stopped                                                                  session.py:287
           INFO     Session stopped                                                                      session.py:174
Traceback (most recent call last):
  File "H:\TGdownload\JH\media_downloader.py", line 376, in <module>
    main()
  File "H:\TGdownload\JH\media_downloader.py", line 360, in main
    updated_config = asyncio.get_event_loop().run_until_complete(
  File "C:\Users\17426\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "H:\TGdownload\JH\media_downloader.py", line 311, in begin_import
    await client.start()
  File "C:\Users\17426\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\methods\utilities\start.py", line 58, in start
    is_authorized = await self.connect()
  File "C:\Users\17426\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\methods\auth\connect.py", line 47, in connect
    await self.session.start()
  File "C:\Users\17426\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\session\session.py", line 142, in start
    raise e
  File "C:\Users\17426\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\session\session.py", line 109, in start
    await self.send(raw.functions.Ping(ping_id=0), timeout=self.START_TIMEOUT)
  File "C:\Users\17426\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\session\session.py", line 333, in send
    raise BadMsgNotification(result.error_code)
pyrogram.errors.BadMsgNotification: [16] The msg_id is too low, the client time has to be synchronized.

**Comment by tapatianbeast** [comment]
Nobody working to fix this? Wow

**Comment by marsnego** [comment]
同样的问题,也是无法运行了

**Comment by Dineshkarthik** [comment]
Updated the custom pyrogam fork this should fix the issue
```sh
pip uninstall pyrogram
pip install https://github.com/Dineshkarthik/pyrogram/archive/refs/heads/master.zip
```
