### ISSUE TITLE
This gets detected

### ISSUE THREAD

**Issue by AlizerUncaged** [Dineshkarthik/telegram_media_downloader#474]
my account got banned for downloading a lot of videos around 5 minutes after running this program, maybe should you put an option to make the download speed, like slow it up or wait around 2 minutes for each media to be downloaded?

**Comment by deanbo83** [comment]
Same here:
           ERROR    Telegram says: [420 FLOOD_WAIT_X] - A wait of 2061 seconds is required (caused by "auth.ExportAuthorization")                                                 client.py:1021
                    Traceback (most recent call last):
                      File "/usr/local/lib/python3.9/dist-packages/pyrogram/client.py", line 878, in get_file
                        exported_auth = await self.invoke(
                      File "/usr/local/lib/python3.9/dist-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
                        r = await self.session.invoke(
                      File "/usr/local/lib/python3.9/dist-packages/pyrogram/session/session.py", line 389, in invoke
                        return await self.send(query, timeout=timeout)
                      File "/usr/local/lib/python3.9/dist-packages/pyrogram/session/session.py", line 357, in send
                        RPCError.raise_it(result, type(data))
                      File "/usr/local/lib/python3.9/dist-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
                        raise getattr(
                    pyrogram.errors.exceptions.flood_420.FloodWait: Telegram says: [420 FLOOD_WAIT_X] - A wait of 2061 seconds is required (caused by "auth.ExportAuthorization")
           INFO     PingTask stopped                                                                                                                                              session.py:291
           INFO     Disconnected                                                                                                                                                connection.py:66

**Comment by azerfr2** [comment]
same with me

**Comment by seeronline** [comment]
stop this program after 99 downloads and restart it again, then it will be okay.

**Comment by azerfr2** [comment]
any update on this matter since 2023??
