### ISSUE TITLE
Integer too big

### ISSUE THREAD

**Issue by csmx1234** [Dineshkarthik/telegram_media_downloader#481]
**Describe the bug**
When I run python media_downloader.py, it exits and says OverflowError: int too big to convert

**To Reproduce**
Share the config: `Please don't share your api_hash & api_id`
```yaml
chat_id: ********
last_read_message_id: 0
ids_to_retry: []
media_types:
- audio
- photo
- video
- document
- voice
- video_note
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all

```

**Python Version**
Python 3.11.6

**OS:**
MacOS 11.6.1

**Logs**
[13:05:59] Telegram Media Downloader v2.0.2,                                              meta.py:18
           Copyright (C) 2019 Dineshkarthik <https://github.com/Dineshkarthik>                      
           Licensed under the terms of the MIT License                                    meta.py:21
                                                                                                    
[13:05:59] INFO     Device: CPython 3.11.6 - Telegram Media Downloader 2.0.2              meta.py:22
           INFO     System: Darwin 20.6.0 (EN)                                            meta.py:23
           INFO     Start creating a new auth key on DC2                                  auth.py:82
           INFO     Connecting...                                                   connection.py:47
[13:06:00] INFO     Connected! Production DC2 - IPv4                                connection.py:54
[13:06:02] INFO     Done auth key exchange: DhGenOk                                      auth.py:267
           INFO     Disconnected                                                    connection.py:66
           INFO     Connecting...                                                   connection.py:47
[13:06:03] INFO     Connected! Production DC2 - IPv4                                connection.py:54
           INFO     NetworkTask started                                               session.py:294
[13:06:04] INFO     Disconnected                                                    connection.py:66
           INFO     NetworkTask stopped                                               session.py:315
           INFO     Session stopped                                                   session.py:180
Traceback (most recent call last):
  File "/Users/csm/Downloads/telegram_media_downloader/media_downloader.py", line 376, in <module>
    main()
  File "/Users/csm/Downloads/telegram_media_downloader/media_downloader.py", line 360, in main
    updated_config = asyncio.get_event_loop().run_until_complete(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/csm/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/csm/Downloads/telegram_media_downloader/media_downloader.py", line 311, in begin_import
    await client.start()
  File "/Users/csm/anaconda3/lib/python3.11/site-packages/pyrogram/methods/utilities/start.py", line 58, in start
    is_authorized = await self.connect()
                    ^^^^^^^^^^^^^^^^^^^^
  File "/Users/csm/anaconda3/lib/python3.11/site-packages/pyrogram/methods/auth/connect.py", line 47, in connect
    await self.session.start()
  File "/Users/csm/anaconda3/lib/python3.11/site-packages/pyrogram/session/session.py", line 149, in start
    raise e
  File "/Users/csm/anaconda3/lib/python3.11/site-packages/pyrogram/session/session.py", line 120, in start
    await self.send(
  File "/Users/csm/anaconda3/lib/python3.11/site-packages/pyrogram/session/session.py", line 318, in send
    message = self.msg_factory(data)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/csm/anaconda3/lib/python3.11/site-packages/pyrogram/session/internals/msg_factory.py", line 37, in __call__
    len(body)
  File "/Users/csm/anaconda3/lib/python3.11/site-packages/pyrogram/raw/core/tl_object.py", line 79, in __len__
    return len(self.write())
               ^^^^^^^^^^^^
  File "/Users/csm/anaconda3/lib/python3.11/site-packages/pyrogram/raw/functions/invoke_with_layer.py", line 78, in write
    b.write(self.query.write())
            ^^^^^^^^^^^^^^^^^^
  File "/Users/csm/anaconda3/lib/python3.11/site-packages/pyrogram/raw/functions/init_connection.py", line 128, in write
    b.write(Int(self.api_id))
            ^^^^^^^^^^^^^^^^
  File "/Users/csm/anaconda3/lib/python3.11/site-packages/pyrogram/raw/core/primitives/int.py", line 33, in __new__
    return value.to_bytes(cls.SIZE, "little", signed=signed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: int too big to convert

**Additional context**

**Comment by capSAR273** [comment]
Having this issue too
