### ISSUE TITLE
downloader is not working on ubuntu 23.10 ( python3.11.6 )

### ISSUE THREAD

**Issue by tshrinivasan** [Dineshkarthik/telegram_media_downloader#489]
**Describe the bug**
downloader is not working on ubuntu 23.10 ( python3.11.6 )

**To Reproduce**
Share the config: `Please don't share your api_hash & api_id`
```yaml
api_hash:  HASH
api_id: API
chat_id: timepasspdf
last_read_message_id: 0
ids_to_retry: []
media_types:
- audio
- document
- photo
- video
- voice
file_formats:
  audio:
  - all
  document:
  - pdf
  - epub
  video:
  - mp4
```

**Python Version**
Python: 3.11.6

**OS:**
The OS and its version: ubuntu 23.10

**Logs**
python3 media_downloader.py 
[19:19:56] Telegram Media Downloader v2.0.2,                                                                                                                      meta.py:18
           Copyright (C) 2019 Dineshkarthik <https://github.com/Dineshkarthik>                                                                                              
           Licensed under the terms of the MIT License                                                                                                            meta.py:21
                                                                                                                                                                            
[19:19:56] INFO     Device: CPython 3.11.6 - Telegram Media Downloader 2.0.2                                                                                      meta.py:22
           INFO     System: Linux 6.5.0-26-generic (EN)                                                                                                           meta.py:23
           INFO     Connecting...                                                                                                                           connection.py:47
           INFO     Connected! Production DC5 - IPv4                                                                                                        connection.py:54
           INFO     NetworkTask started                                                                                                                       session.py:294
[19:19:57] INFO     Session initialized: Layer 158                                                                                                            session.py:139
           INFO     Device: CPython 3.11.6 - Pyrogram 2.0.106                                                                                                 session.py:140
           INFO     System: Linux 6.5.0-26-generic (en)                                                                                                       session.py:141
           INFO     Session started                                                                                                                           session.py:155
           INFO     PingTask started                                                                                                                          session.py:272
[19:19:58] INFO     Started 8 HandlerTasks                                                                                                                 dispatcher.py:154
Traceback (most recent call last):
  File "/home/shrini/.local/lib/python3.11/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 62, in resolve_peer
    return await self.storage.get_peer_by_id(peer_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shrini/.local/lib/python3.11/site-packages/pyrogram/storage/sqlite_storage.py", line 142, in get_peer_by_id
    raise KeyError(f"ID not found: {peer_id}")
KeyError: 'ID not found: timepasspdf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shrini/.local/lib/python3.11/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 71, in resolve_peer
    int(peer_id)
ValueError: invalid literal for int() with base 10: 'timepasspdf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shrini/.local/lib/python3.11/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 74, in resolve_peer
    return await self.storage.get_peer_by_username(peer_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shrini/.local/lib/python3.11/site-packages/pyrogram/storage/sqlite_storage.py", line 154, in get_peer_by_username
    raise KeyError(f"Username not found: {username}")
KeyError: 'Username not found: timepasspdf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shrini/telegram/timepasspdf/media_downloader.py", line 376, in <module>
    main()
  File "/home/shrini/telegram/timepasspdf/media_downloader.py", line 360, in main
    updated_config = asyncio.get_event_loop().run_until_complete(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/shrini/telegram/timepasspdf/media_downloader.py", line 327, in begin_import
    async for message in messages_iter:  # type: ignore
  File "/home/shrini/.local/lib/python3.11/site-packages/pyrogram/methods/messages/get_chat_history.py", line 115, in get_chat_history
    messages = await get_chunk(
               ^^^^^^^^^^^^^^^^
  File "/home/shrini/.local/lib/python3.11/site-packages/pyrogram/methods/messages/get_chat_history.py", line 42, in get_chunk
    peer=await client.resolve_peer(chat_id),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shrini/.local/lib/python3.11/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 76, in resolve_peer
    await self.invoke(
  File "/home/shrini/.local/lib/python3.11/site-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shrini/.local/lib/python3.11/site-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shrini/.local/lib/python3.11/site-packages/pyrogram/session/session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "/home/shrini/.local/lib/python3.11/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.UsernameNotOccupied: Telegram says: [400 USERNAME_NOT_OCCUPIED] - The username is not occupied by anyone (caused by "contacts.ResolveUsername")

**Additional context**

**Comment by Dineshkarthik** [comment]
Using chat/group id instead of username will solve the issue.
