### ISSUE TITLE
The msg_id is too low, the client time has to be synchronized.

### ISSUE THREAD

**Issue by zinsser901224** [Dineshkarthik/telegram_media_downloader#491]
**Describe the bug**
script doesn't work

**To Reproduce**
Share the config: `Please don't share your api_hash & api_id`
```yaml
chat_id: telegram_chat_id
last_read_message_id: 0
media_types:
- audio
- photo
- video
- document
- voice
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
```

**Python Version**
Python: 3.11.1

**OS:**
win11

**Logs**
[22:59:45] Telegram Media Downloader v2.0.2,                                                                  meta.py:18
           Copyright (C) 2019 Dineshkarthik <https://github.com/Dineshkarthik>
           Licensed under the terms of the MIT License                                                        meta.py:21

[22:59:45] INFO     Device: CPython 3.11.1 - Telegram Media Downloader 2.0.2                                  meta.py:22
           INFO     System: Windows 10 (EN)                                                                   meta.py:23
[22:59:47] INFO     Using proxy 127.0.0.1                                                                      tcp.py:72
           INFO     Connecting...                                                                       connection.py:56
           INFO     Connected! Production DC5 - IPv4 - TCPAbridgedO                                     connection.py:63
           INFO     NetworkTask started                                                                   session.py:271
           INFO     Time synced: 2024-05-02 14:59:47.388562 UTC                                             msg_id.py:45
           INFO     Disconnected                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                   session.py:287
           INFO     Session stopped                                                                       session.py:174
Traceback (most recent call last):
  File "F:\Programs\telegram_media_downloader-2.0.2\media_downloader.py", line 376, in <module>
    main()
  File "F:\Programs\telegram_media_downloader-2.0.2\media_downloader.py", line 360, in main
    updated_config = asyncio.get_event_loop().run_until_complete(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\programs\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "F:\Programs\telegram_media_downloader-2.0.2\media_downloader.py", line 311, in begin_import
    await client.start()
  File "F:\programs\Python311\Lib\site-packages\pyrogram\methods\utilities\start.py", line 58, in start
    is_authorized = await self.connect()
                    ^^^^^^^^^^^^^^^^^^^^
  File "F:\programs\Python311\Lib\site-packages\pyrogram\methods\auth\connect.py", line 47, in connect
    await self.session.start()
  File "F:\programs\Python311\Lib\site-packages\pyrogram\session\session.py", line 142, in start
    raise e
  File "F:\programs\Python311\Lib\site-packages\pyrogram\session\session.py", line 109, in start
    await self.send(raw.functions.Ping(ping_id=0), timeout=self.START_TIMEOUT)
  File "F:\programs\Python311\Lib\site-packages\pyrogram\session\session.py", line 333, in send
    raise BadMsgNotification(result.error_code)
pyrogram.errors.BadMsgNotification: [16] The msg_id is too low, the client time has to be synchronized.

**Additional context**
I've synchonized my pc time in settings

**Comment by zinsser901224** [comment]
I found the solution

**Comment by zinsser901224** [comment]
I found the solution
