### ISSUE TITLE
pyrogram.errors.BadMsgNotification: [16] The msg_id is too low, the client time has to be synchronized.

### ISSUE THREAD

**Issue by dan3577** [Dineshkarthik/telegram_media_downloader#500]
run: python media_downloader.py

error: pyrogram.errors.BadMsgNotification: [16] The msg_id is too low, the client time has to be synchronized.

config.yaml:

chat_id: telegram_chat_id
last_read_message_id: 0
media_types:
- audio
- document
- photo
- video
- voice
file_formats:
  audio:
  - all
  document:
  - pdf
  - epub
  video:
  - mp4
  

PS C:\Users\86101\Downloads\telegram_media_downloader-2.0.2> python media_downloader.py
[15:41:08] Telegram Media Downloader v2.0.2,                                                                  meta.py:18
           Copyright (C) 2019 Dineshkarthik <https://github.com/Dineshkarthik>
           Licensed under the terms of the MIT License                                                        meta.py:21

[15:41:08] INFO     Device: CPython 3.12.4 - Telegram Media Downloader 2.0.2                                  meta.py:22
           INFO     System: Windows 11 (EN)                                                                   meta.py:23
           INFO     Using proxy 192.168.2.105:7890                                                             tcp.py:72
           INFO     Connecting...                                                                       connection.py:56
           INFO     Connected! Production DC5 - IPv4 - TCPAbridgedO                                     connection.py:63
           INFO     NetworkTask started                                                                   session.py:272
[15:41:09] INFO     Time synced: 2024-12-19 07:41:04.655605 UTC                                             msg_id.py:45
           INFO     Disconnected                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                   session.py:288
           INFO     Session stopped                                                                       session.py:174
Traceback (most recent call last):
  File "C:\Users\86101\Downloads\telegram_media_downloader-2.0.2\media_downloader.py", line 376, in <module>
    main()
  File "C:\Users\86101\Downloads\telegram_media_downloader-2.0.2\media_downloader.py", line 360, in main
    updated_config = asyncio.get_event_loop().run_until_complete(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86101\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\86101\Downloads\telegram_media_downloader-2.0.2\media_downloader.py", line 311, in begin_import
    await client.start()
  File "C:\Users\86101\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyrogram\methods\utilities\start.py", line 52, in start
    is_authorized = await self.connect()
                    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86101\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyrogram\methods\auth\connect.py", line 46, in connect
    await self.session.start()
  File "C:\Users\86101\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyrogram\session\session.py", line 142, in start
    raise e
  File "C:\Users\86101\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyrogram\session\session.py", line 109, in start
    await self._send(raw.functions.Ping(ping_id=0), timeout=self.START_TIMEOUT)
  File "C:\Users\86101\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyrogram\session\session.py", line 334, in _send
    raise BadMsgNotification(result.error_code)
pyrogram.errors.BadMsgNotification: [16] The msg_id is too low, the client time has to be synchronized.

**Comment by 1158191255** [comment]
You need a America VPN
