### ISSUE TITLE
ValueError: list.remove(x): x not in list

### ISSUE THREAD

**Issue by Bo0oM** [Dineshkarthik/telegram_media_downloader#58]
**ValueError: list.remove(x): x not in list**

```
Traceback (most recent call last):
  File "/tmp/telegram_media_downloader/media_downloader.py", line 289, in <module>
    updated_config = asyncio.get_event_loop().run_until_complete(
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/tmp/telegram_media_downloader/media_downloader.py", line 261, in begin_import
    last_read_message_id = await process_messages(
  File "/tmp/telegram_media_downloader/media_downloader.py", line 210, in process_messages
    message_ids = await asyncio.gather(
  File "/tmp/telegram_media_downloader/media_downloader.py", line 167, in download_media
    download_path = manage_duplicate_file(download_path)
  File "/tmp/telegram_media_downloader/utils/file_management.py", line 65, in manage_duplicate_file
    old_files.remove(file_path)
ValueError: list.remove(x): x not in list
```

**Comment by Dineshkarthik** [comment]
@Bo0oM can you update the above issue using the `Bug Report` template so that it will be easy to reproduce this issue.
